⚡Feat/font: 폰트 용량 최적화 (dynamic subset)
ISEGYE-Universe/frontend pull request #36
Opened 2023-11-13 15:20 UTC by rnintai

# 개요
폰트 용량 문제로 인해 최적화된 dynamic subset web font로 변경 (CDN)

## 카테고리

- [ ] Bug fix (not modifying existing features)
- [ ] New feature (not modifying existing features)
- [x] Changing feature (modifying existing feature or fixing bug)
- [ ] Docs updated required

- [ ] Bug fix
- [ ] Add Feature
- [ ] Change Feature
- [ ] Chore

# 상세 내용
- 이안님께서 작업해주신 최적화 폰트 적용
  - Dynamic Subset, 지원 언어 축소 (KR, EN), CDN 배
- ++ CDN 링크를 `Global.tsx` 내 저 부분에 넣는게 맞을 지 리뷰 부탁드립니다!

2023-11-13 15:21 UTC, kms0219kms requested changes
/fonts/NotoSansCJKkr-*.otf 삭제해도 좋을 것 같습니다.

2023-11-13 15:22 UTC, kms0219kms requested changes
link 태그 말고, css에 @import문 쓰는게 더 좋을것 같아요(NextJs이슈때문에)

2023-11-13 15:33 UTC, rnintai commented
> /fonts/NotoSansCJKkr-*.otf 삭제해도 좋을 것 같습니다.
> link 태그 말고, css에 https://github.com/import문 쓰는게 더 좋을것 같아요(NextJs이슈때문에)

두 부분 수정 완료되었습니다! 확인 부탁드립니다

2023-11-13 15:46 UTC, kms0219kms approved these changes

2023-11-14 14:24 UTC, stripy1026 approved these changes
킹아띠!

![따봉릴파](https://github.com/ISEGYE-Universe/frontend/assets/62825700/b2ca4ac2-2158-49cf-9a23-9edb75a43464)

2023-11-18 04:42 UTC, merged