[FIX] 메인 페이지 Artist 섹션 ESLint 에 맞춰서 수정
ISEGYE-Universe/frontend pull request #47
Opened 2023-11-18 07:26 UTC by stripy1026

# 개요

연관 이슈 없음

마크업 변경사항 없음

## 카테고리

- [ ] Bug fix (not modifying existing features)
- [ ] New feature (not modifying existing features)
- [ ] Changing feature (modifying existing feature or fixing bug)
- [ ] Docs updated required

- [ ] Bug fix
- [ ] Add Feature
- [ ] Change Feature
- [ ] Chore

# 상세 내용

Component definition rule 부분은 수정하지 않음 (추후 논의 필요할 것으로 예상했음)
나머지 부분은 ESLint 에러 없음 확인

2023-11-19 01:13 UTC, rnintai requested changes
컴포넌트 정의부 관련 의사결정 이후에 추가 수정이 필요할 것으로 보입니다!!
일단 Request changes로 남겨두겠습니다

2023-11-20 23:55 UTC, rnintai commented
> 컴포넌트 정의부 관련 의사결정 이후에 추가 수정이 필요할 것으로 보입니다!! 일단 Request changes로 남겨두겠습니다

@stripy1026 
`import/prefer-default-export` 관련 수정 진행 부탁드립니당!

2023-11-22 13:19 UTC, stripy1026 commented
ARTIST 섹션 eslint fix 완료했습니다

2023-11-22 14:34 UTC, rnintai approved these changes
LGTM

2023-11-24 11:18 UTC, kms0219kms approved these changes
LGTM

2023-11-24 11:18 UTC, merged