메인 페이지 News 섹션 ESLint fix
ISEGYE-Universe/frontend pull request #49
Opened 2023-11-18 07:39 UTC by stripy1026

# 개요

관련 이슈 없음

마크업 변경 없음

## 카테고리

- [ ] Bug fix (not modifying existing features)
- [ ] New feature (not modifying existing features)
- [ ] Changing feature (modifying existing feature or fixing bug)
- [ ] Docs updated required
- [ ] Chore

# 상세 내용

component definition rule 관련사항은 수정하지 않음 (lint: prefer-default-export)
앞선 PR과 동일하게 이 부분은 수정 방식 논의 필요하다고 느낌

나머지 ESLint 룰은 수정 완료

2023-11-19 01:14 UTC, rnintai requested changes
수고하셨습니다! 마찬가지로 컴포넌트 정의부 lint룰 관련 의사결정 이후에 Approve로 넘기겠습니다.

2023-11-20 23:56 UTC, rnintai commented
> 수고하셨습니다! 마찬가지로 컴포넌트 정의부 lint룰 관련 의사결정 이후에 Approve로 넘기겠습니다.

@stripy1026 
마찬가지로 `import/prefer-default-export`룰 관련 수정 진행 부탁드립니당!

2023-11-25 10:23 UTC, rnintai approved these changes
LGTM

2023-11-26 09:18 UTC, HeoYoungJin98 approved these changes
수고하셨습니다 merge 하겠습니다

2023-11-26 09:18 UTC, merged