feat/chart-page: 레이아웃(최근 명예의 전당 + 역대 기록 영역 + Top100 차트) + eslint fix
ISEGYE-Universe/frontend pull request #57
Opened 2023-11-22 01:45 UTC by rnintai

# 개요
![image](https://github.com/ISEGYE-Universe/frontend/assets/65759076/3af5c85e-4b87-4cb0-a968-1e5c1579d499)
![image](https://github.com/ISEGYE-Universe/frontend/assets/65759076/b2ca7383-ce1a-434d-9b79-f9c48a592db3)
![image](https://github.com/ISEGYE-Universe/frontend/assets/65759076/053d807a-2db8-4a1d-93fa-523bab2528d1)

## 카테고리

- [ ] Bug fix (not modifying existing features)
- [x] New feature (not modifying existing features)
- [ ] Changing feature (modifying existing feature or fixing bug)
- [ ] Docs updated required
- [ ] Chore

# 상세 내용
- 더미 데이터 사용
- 최근 디자인 변경사항 반영
- Top100 차트 `chart.js` 활용하여 마크업
- eslint fix

2023-11-22 13:39 UTC, stripy1026 requested changes

2023-11-25 01:52 UTC, rnintai commented on src/components/Chart/AlbumNewsCard.tsx
> +export const AlbumNewsCard = (prop: AlbumNewsCardProps) => {
해결했습니다!

2023-11-28 00:28 UTC, HeoYoungJin98 approved these changes
수고하셨습니다

2023-11-29 13:27 UTC, kms0219kms approved these changes
LGTM

2023-11-29 14:23 UTC, rnintai commented
@stripy1026 수정 완료했습니다~

2023-12-03 09:16 UTC, kms0219kms commented
#53 머지하고 커밋 꼬인거 고쳐서 머지합시다

2023-12-03 09:29 UTC, rnintai commented
> #53 머지하고 커밋 꼬인거 고쳐서 머지합시다

#51 이랑 #50 나눠서 작업하다가 서로 머지해버렸던걸로 기억합니다 ㅋㅋㅋ..

2023-12-03 10:46 UTC, stripy1026 approved these changes
고생하셨습니다!

![릴파-햝짝](https://github.com/ISEGYE-Universe/frontend/assets/62825700/4f9fa451-566f-4345-9976-ed4c865cb1c1)

2023-12-03 10:48 UTC, merged