Feat/chart-page: 차트 영역 visx로 변경하여 구현, 가장 최근 데이터 말풍선 추가
ISEGYE-Universe/frontend pull request #98
Opened 2023-12-23 03:49 UTC by rnintai

# 개요
- Closes #93 
![image](https://github.com/ISEGYE-Universe/frontend/assets/65759076/4504370d-417b-4004-8f54-3cb791d68dc7)

## 카테고리
- [x] Change Feature

# 상세 내용
- `querySelector`을 활용하여 좌표값 가져왔습니다.
  - 개선하려 했으나 방법을 찾지 못함

2023-12-24 16:04 UTC, stripy1026 requested changes
querySelector 쓰는부분은 보고있는데 visx 를 써본적이 없어서 구조를 파악하기가 되게 힘드네요 ..ㅠ
나중에 한번 설명해주시면 리팩토링 할 방법을 함께 찾아볼 수 있을것같습니당

린트 에러는 고쳐야 할 것 같아서 일단 Request changes 달아놓겠습니다!

2023-12-24 16:04 UTC, stripy1026 commented on src/components/Chart/Top100Chart.tsx
> +  useEffect(() => {
제 환경에서는 이 함수에서 린트 에러 뜨네요

![image](https://github.com/ISEGYE-Universe/frontend/assets/62825700/97dadb49-3ed6-4599-b7ed-29071ca8f537)

2023-12-25 10:08 UTC, rnintai commented on src/components/Chart/HistoryCarousel.tsx
> +          {[...dummyData].map((data) => (
spread는 제가 수정하다가 놓쳤네요 ㅎㅎ 감사합니다. 그리고 말씀주신 방법 차용해서 커밋하겠습니다

2023-12-25 10:11 UTC, rnintai commented on src/components/Chart/Top100Chart.tsx
> +  useEffect(() => {
최초 1회 실행하기 위해 의존성 배열을 비워두었는데요, lint warn이 뜨긴 합니다. 문제 소지 있다면 다른 방법을 생각해볼게요! 감사합니다

2023-12-25 12:50 UTC, stripy1026 approved these changes

2023-12-25 12:50 UTC, merged